# Arrays

In [12]:
import numpy
def arrays(arr):
    # complete this function
    # use numpy.array
    numpyarr =numpy.array(arr[::-1],float)
    return numpyarr
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9 -10
[-10.   9.   8.   7.   6.   5.   4.   3.   2.   1.]


# Shape and Reshape

In [19]:
import numpy
arr = input().strip().split(' ')
reshaped_3x3 = numpy.reshape(arr,(3,3))
converted_array = reshaped_3x3.astype(int)
print(converted_array)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten



In [72]:
import numpy
N, M = map(int,input().split())
l = []
for i in range(N):
    l.append(input().strip().split())
num_array = numpy.array(l,dtype = int)
print(num_array.transpose())
print(num_array.flatten())


5 4
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16
17 18 19 20
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Concatenate



In [86]:
import numpy
N,M,P = map(int,input().split())
mat1 = []
mat2 = []
for i in range(N):
    mat1.append(input().strip().split())
for j in range(M):
    mat2.append(input().strip().split())
numpy_arr1 = numpy.array(mat1)
arr1 = numpy_arr1.astype(int)
numpy_arr2 = numpy.array(mat2)
arr2 = numpy_arr2.astype(int)
print(numpy.concatenate((arr1,arr2),axis=0))

3 4 2
1 2
1 5
3 6
5 6
6 5
9 5
3 2
[[1 2]
 [1 5]
 [3 6]
 [5 6]
 [6 5]
 [9 5]
 [3 2]]


# Zeros and Ones



In [92]:
import numpy
ones_zeros= tuple(map(int,input().split()))
print(numpy.zeros(ones_zeros,dtype = int))
print(numpy.ones(ones_zeros,dtype = int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [95]:
import numpy
numpy.set_printoptions(legacy='1.13')
N , M = map(int,input().split())
print(numpy.eye(N,M))

5 5
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


# Array Mathematics



In [100]:
import numpy
N, M  = map(int,input().split())
arr1 = numpy.array([input().split() for i in range(N)],dtype = int)
arr2 = numpy.array([input().split() for i in range(N)],dtype = int)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)
print(arr1%arr2)
print(arr1**arr2)

1 4
1 2 3 4
6 3 9 8
[[ 7  5 12 12]]
[[-5 -1 -6 -4]]
[[ 6  6 27 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1     8 19683 65536]]


# Floor, Ceil and Rint



In [105]:
import numpy
numpy.set_printoptions(legacy='1.13')
num_arr = list(map(float,input().strip().split()))
print(numpy.floor(num_arr))
print(numpy.ceil(num_arr))
print(numpy.rint(num_arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 9.8 8.9 10.5
[  1.   2.   3.   4.   5.   6.   7.   9.   8.  10.]
[  2.   3.   4.   5.   6.   7.   8.  10.   9.  11.]
[  1.   2.   3.   4.   6.   7.   8.  10.   9.  10.]


# Sum and Prod

In [110]:
import numpy
N ,M = map(int,input().split())
nump_arr =numpy.array([input().split() for i in range(N)],dtype=int)
summation =(numpy.sum(nump_arr,axis=0))
print(numpy.prod(summation))

2 3
1 2 3
4 5 6
315


# Min and Max



In [111]:
import numpy
N,M = map(int,input().split())
numm_arr = numpy.array([input().split() for i in range(N)],dtype = int)
minimum =numpy.min(numm_arr,axis=1)
print(numpy.max(minimum))

3 2
1 2
3 4
5 6
5


# Mean, Var, and Std



In [8]:
import numpy 
N,M = map(int,input().split())
numpp_arr = numpy.array([input().split() for i in range(N)],dtype=float)
print(numpy.mean(numpp_arr,axis=1))
print(numpy.var(numpp_arr,axis=0))
print(round(numpy.std(numpp_arr,axis=None),11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


# Dot and Cross



In [11]:
import numpy 
N = int(input())
mat1 =numpy.array([input().split() for i in range(N)],dtype= int)
mat2 =numpy.array([input().split() for i in range(N)],dtype= int)
mulmat = numpy.dot(mat1,mat2)
print(mulmat)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer



In [20]:
import numpy
mat1_ele = input().split()
mat2_ele = input().split()
matr_1 = numpy.array(mat1_ele,dtype=int)
matr_2 = numpy.array(mat2_ele,dtype =int)
print(numpy.inner(matr_1,matr_2))
print(numpy.outer(matr_1,matr_2))

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomials



In [26]:
import numpy
coefficients = [float(i) for i in input().split()]
x = float(input())
poly_val = numpy.polyval(coefficients,x)
print(poly_val)

1.5 2 3 4
1
10.5


# Linear Algebra



In [4]:
import numpy
N= int(input())
num_array = numpy.array([input().split() for i in range(N)],dtype = float)
deter = round(numpy.linalg.det(num_array),2)
print(deter)

2
1.1 1.1
1.1 1.1
0.0
